pipeline {
    agent any

    environment{
        PROJECT_DIR = 'Student-management-application'
    }
    stages{
        stage('Cloning Git repositories'){
            steps{
                script{
                    withCredentials([usernamePassword(
                        credentialsId: 'GIT_CRED',
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_PASSWORD'
                    )]){
                        sh '''
                            mkdir -p $PROJECT_DIR
                            cd $PROJECT_DIR
                            echo "Triggered Repo is: $REPO_NAME"

                            if [ "$REPO_NAME" = "Student_management_application_backend" ]; then
                                echo "Removing existing backend repo directory (if any)..."
                                rm -rf Student_management_application_backend
                                echo "Cloning backend repo..."
                                git clone https://github.com/priyanshusaineni/Student_management_application_backend.git
                            elif [ "$REPO_NAME" = "Student_management_application_frontend" ]; then
                                echo "Removing existing frontend repo directory (if any)..."
                                rm -rf Student_management_application_frontend
                                echo "Cloning frontend repo..."
                                git clone https://github.com/priyanshusaineni/Student_management_application_frontend.git
                            else
                                echo "No matching repository to clone."
                            fi                            
                        '''
                    }
                }
                
            }
        }

        stage('Build Docker images'){
            steps{
                script{
                    sh '''
                        cd $PROJECT_DIR

                        sudo docker network create app_network || true

                        if [ "$REPO_NAME" = "Student_management_application_backend" ]; then
                            echo "Building only Backend image ..."       
                            sudo docker build -t $DOCKERHUB_USERNAME/backend ./Student_management_application_backend
                        elif [ "$REPO_NAME" = "Student_management_application_frontend" ]; then
                            echo "Building only frontend image ..."
                            sudo docker build -t $DOCKERHUB_USERNAME/frontend ./Student_management_application_frontend
                        else
                            echo "There are no updates in the repository..."
                        fi
                    '''
                }
            }
        }

        stage('Pushing Images to Docker hub'){
            steps{
                script{
                    withCredentials([usernamePassword(
                        credentialsId: 'DOCKERHUB_CRED',
                        usernameVariable: 'DOCKERHUB_USR',
                        passwordVariable: 'DOCKERHUB_PASSWD'
                    )]){
                        sh '''
                            echo "$DOCKERHUB_PASSWD" | sudo docker login -u "$DOCKERHUB_USR" --password-stdin 

                            if [ "$REPO_NAME" = "Student_management_application_backend" ]; then
                                echo "Pushing only Backend image ..."  
                                sudo docker push $DOCKERHUB_USERNAME/backend 
                            elif [ "$REPO_NAME" = "Student_management_application_frontend" ]; then
                                echo "Pushing only frontend image ..."
                                sudo docker push $DOCKERHUB_USERNAME/frontend
                            else
                                echo "There are no updates in the repository..."
                            fi
                        '''
                    }
                    
                }
            }
        }

        stage('Deploy to EC2 (smaller instance)') {
            steps {
                withCredentials([sshUserPrivateKey(
                    credentialsId: 'ec2-smaller-instance',
                    keyFileVariable: 'KEY_FILE',
                    usernameVariable: 'INSTANCE_USER'
                )]) {
                    script {
                        sh '''
                            ssh -o StrictHostKeyChecking=no -i $KEY_FILE $INSTANCE_USER@$IP_ADDRESS "mkdir -p ~/Student-management-application/Student_management_application_frontend"
                        
                            scp -o StrictHostKeyChecking=no -i $KEY_FILE \
                            Student-management-application/Student_management_application_frontend/docker-compose.yml \
                            $INSTANCE_USER@$IP_ADDRESS:~/Student-management-application/Student_management_application_frontend/
                    
                            ssh -o StrictHostKeyChecking=no -i $KEY_FILE $INSTANCE_USER@$IP_ADDRESS " \
                                cd ~/Student-management-application/Student_management_application_frontend && \
                                docker-compose down || true && \
                                docker-compose up -d --build \
                            "
                        '''
                    }
                }
            }
        }
    }
}